package com.apis.controller;

import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Created by Ashiwani on 22/01/19.
 */

@RestController()
@RequestMapping(value = "/v1", consumes = "application/json", produces = "application/json")
public class MockApi {

	String get_plan_avail_v2 = "{\r\n  \"data\": [\r\n    {\r\n      \"store_id\": 12323,\r\n      \"product_id\": \"SHYIO3Z30F\",\r\n      \"variations\": [\r\n        {\r\n          \"id\": \"4_1\",\r\n          \"spin\": \"RBZBK3IJ9X\",\r\n          \"availability\": {\r\n            \"is_avail\": false,\r\n            \"next_change\": 127429,\r\n            \"message\": \"\"\r\n          },\r\n          \"inventory\": {\r\n            \"remaining\": 0,\r\n            \"message\": \"\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_2\",\r\n          \"spin\": \"JBZBK3IJ0X\",\r\n          \"availability\": {\r\n            \"is_avail\": false,\r\n            \"next_change\": 127429,\r\n            \"message\": \"\"\r\n          },\r\n          \"inventory\": {\r\n            \"remaining\": 0,\r\n            \"message\": \"\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_3\",\r\n          \"spin\": \"JRZBJ3IJ0X\",\r\n          \"availability\": {\r\n            \"is_avail\": false,\r\n            \"next_change\": 127429,\r\n            \"message\": \"\"\r\n          },\r\n          \"inventory\": {\r\n            \"remaining\": 0,\r\n            \"message\": \"\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_4\",\r\n          \"spin\": \"RBZBK3IJ9X\",\r\n          \"availability\": {\r\n            \"is_avail\": false,\r\n            \"next_change\": 127429,\r\n            \"message\": \"\"\r\n          },\r\n          \"inventory\": {\r\n            \"remaining\": 0,\r\n            \"message\": \"\"\r\n          }\r\n        }\r\n        \r\n      ]\r\n    }\r\n  ]\r\n}\r\n";
	String get_plan_meta_v2 = "{\r\n  \"data\": [\r\n    {\r\n      \"product_id\": \"SHYIO3Z30F\",\r\n      \"store_id\": 12323,\r\n      \"meta\": {\r\n        \"display_name\": \"North Indian Plan\",\r\n        \"long_description\": \"something\",\r\n        \"is_veg\": 1,\r\n        \"cuisine\": \"Indian\",\r\n        \"calorific_info\": \"low cal\",\r\n        \"preparation_type\": \"KETO\",\r\n        \"spice_level\": \"low spicy\",\r\n        \"ingredients\": [\r\n          \"Garam Masala\"\r\n        ]\r\n      },\r\n      \"variations\": [\r\n        {\r\n          \"id\": \"4_1\",\r\n          \"spin\": \"JBZBK3IJ0X\",\r\n          \"images\": [\r\n            \"Swiggy-Daily/f7cgdflaxlt4iyyonffy\"\r\n          ],\r\n          \"default\": false,\r\n          \"price\": {\r\n            \"price\": 9000,\r\n            \"currency\": \"PAISA\"\r\n          },\r\n          \"meta\": {\r\n            \"tenure\": 3,\r\n            \"tenure_type\": \"MEAL\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_2\",\r\n          \"spin\": \"GBZRK3GJ0M\",\r\n          \"images\": [\r\n            \"Swiggy-Daily/f7cgdflaxlt4iyyonffy\"\r\n          ],\r\n          \"default\": false,\r\n          \"price\": {\r\n            \"price\": 8000,\r\n            \"currency\": \"PAISA\"\r\n          },\r\n          \"meta\": {\r\n            \"tenure\": 7,\r\n            \"tenure_type\": \"MEAL\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_3\",\r\n          \"spin\": \"GBZRK3GJ0M\",\r\n          \"images\": [\r\n            \"Swiggy-Daily/f7cgdflaxlt4iyyonffy\"\r\n          ],\r\n          \"default\": false,\r\n          \"price\": {\r\n            \"price\": 7000,\r\n            \"currency\": \"PAISA\"\r\n          },\r\n          \"meta\": {\r\n            \"tenure\": 15,\r\n            \"tenure_type\": \"MEAL\"\r\n          }\r\n        },\r\n        {\r\n          \"id\": \"4_4\",\r\n          \"spin\": \"G4ZRK3GJ0M\",\r\n          \"images\": [\r\n            \"Swiggy-Daily/f7cgdflaxlt4iyyonffy\"\r\n          ],\r\n          \"default\": false,\r\n          \"price\": {\r\n            \"price\": 6000,\r\n            \"currency\": \"PAISA\"\r\n          },\r\n          \"meta\": {\r\n            \"tenure\": 30,\r\n            \"tenure_type\": \"MEAL\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}\r\n";

	String get_prod_avail_v2 = "{\r\n  \"data\": [\r\n    {\r\n      \"store_id\": 12323,\r\n      \"product_id\": \"SHYIO3Z30F\",\r\n      \"variations\": [\r\n        {\r\n          \"id\": \"4_1\",\r\n          \"spin\": \"RBZBK3IJ9X\",\r\n          \"availability\": {\r\n            \"is_avail\": false,\r\n            \"next_change\": 127429,\r\n            \"message\": \"\"\r\n          },\r\n          \"inventory\": {\r\n            \"remaining\": 0,\r\n            \"message\": \"\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}\r\n";

	String get_prod_meta_v2 = "{\r\n  \"data\": [\r\n    {\r\n      \"product_id\": \"SHYIO3Z30F\",\r\n      \"store_id\": 12323,\r\n      \"meta\": {\r\n        \"display_name\": \"North Indian Meal\",\r\n        \"short_decription\": \"something\",\r\n        \"is_veg\": 1,\r\n        \"cuisine\": \"Indian\",\r\n        \"calorific_info\": \"low cal\",\r\n        \"preparation_type\": \"KETO\",\r\n        \"spice_level\": \"low spicy\",\r\n        \"ingredients\": [\r\n          \"Garam Masala\"\r\n        ]\r\n      },\r\n      \"variations\": [\r\n        {\r\n          \"id\": \"4_1\",\r\n          \"spin\": \"JBZBK3IJ0X\",\r\n          \"images\": [\r\n            \"Swiggy-Daily/f7cgdflaxlt4iyyonffy\"\r\n          ],\r\n          \"default\": true,\r\n          \"price\": {\r\n            \"price\": 9000,\r\n            \"currency\": \"PAISA\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}\r\n";
	String get_meals_availability = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 5\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 50\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1254393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 5\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 1\n      }\n    },\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 5\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 50\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1254393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 5\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 1\n      }\n    }\n  ]\n}";

	String get_meals_meta = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"dal roti with rice\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"sku_name\": \"chole chawal\",\n      \"price\": 90.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chole_chawal.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"sku_name\": \"chicken biryani raita\",\n      \"price\": 201.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chicken_birayni.png\",\n      \"attributes\": {\n        \"is_veg\": 0\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"sku_name\": \"dal roti with rice\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"dal roti with rice\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"sku_name\": \"chole chawal\",\n      \"price\": 90.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chole_chawal.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"sku_name\": \"chicken biryani raita\",\n      \"price\": 201.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chicken_birayni.png\",\n      \"attributes\": {\n        \"is_veg\": 0\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"sku_name\": \"dal roti with rice\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    }\n  ]\n}";

	String get_plans_availability = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"variations\": [\n        {\n          \"tenure\": 3,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 7,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 15,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        }\n      ]\n    },{\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"variations\": [\n        {\n          \"tenure\": 3,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 7,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 15,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        }\n      ]\n    },{\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"variations\": [\n        {\n          \"tenure\": 3,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 7,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        },\n        {\n          \"tenure\": 15,\n          \"availability\": {\n            \"is_open\": true,\n            \"next_change_time\": 1214393434\n          },\n          \"inventory\": {\n            \"remaining_count\": 5\n          }\n        }\n      ]\n    }\n  ]\n}";

	String get_plans_meta = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"plan 1\",\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      },\n      \"variations\": [\n        {\n          \"price\": 40,\n          \"tenure\": 3\n        },\n        {\n          \"price\": 35,\n          \"tenure\": 7\n        },\n        {\n          \"price\": 30,\n          \"tenure\": 15\n        }\n      ]\n    },\n    {\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"plan 1\",\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      },\n      \"variations\": [\n        {\n          \"price\": 40,\n          \"tenure\": 3\n        },\n        {\n          \"price\": 35,\n          \"tenure\": 7\n        },\n        {\n          \"price\": 30,\n          \"tenure\": 15\n        }\n      ]\n    },\n    {\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"plan 1\",\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      },\n      \"variations\": [\n        {\n          \"price\": 40,\n          \"tenure\": 3\n        },\n        {\n          \"price\": 35,\n          \"tenure\": 7\n        },\n        {\n          \"price\": 30,\n          \"tenure\": 15\n        }\n      ]\n    },\n    {\n      \"plan_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"plan 1\",\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\"\n      },\n      \"variations\": [\n        {\n          \"price\": 40,\n          \"tenure\": 3\n        },\n        {\n          \"price\": 35,\n          \"tenure\": 7\n        },\n        {\n          \"price\": 30,\n          \"tenure\": 15\n        }\n      ]\n    }\n  ]\n}";

	String addon_list_json = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"chatani\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"sku_name\": \"curd\",\n      \"price\": 90.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chole_chawal.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"sku_name\": \"raita\",\n      \"price\": 201.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chicken_birayni.png\",\n      \"attributes\": {\n        \"is_veg\": 0\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"sku_name\": \"jamooon\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },{\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"sku_name\": \"chatani\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 2341,\n      \"store_id\": 1,\n      \"sku_name\": \"curd\",\n      \"price\": 90.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chole_chawal.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    },\n    {\n      \"sku_id\": 523,\n      \"store_id\": 2,\n      \"sku_name\": \"raita\",\n      \"price\": 201.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/chicken_birayni.png\",\n      \"attributes\": {\n        \"is_veg\": 0\n      }\n    },\n    {\n      \"sku_id\": 234,\n      \"store_id\": 2,\n      \"sku_name\": \"jamooon\",\n      \"price\": 101.99,\n      \"enabled\": true,\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1\n      }\n    }\n  ]\n}";

	String checkout_plan_meta = "{\n  \"request_id\": \"9023foi8sof3h4lskzkf8o4wbfo8\",\n  \"status_code\": \"LIST-0001\",\n  \"status_message\": \"something\",\n  \"data\": [\n    {\n      \"sku_id\": 1232,\n      \"store_id\": 1,\n      \"category_id\": 21,\n      \"sku_name\": \"plan 1\",\n      \"image_url\": \"www.aws-s3.swiggy.in/dal_roti_with_rice.png\",\n      \"attributes\": {\n        \"is_veg\": 1,\n        \"cuisine\": \"Indian\",\n        \"calorific_info\": \"low cal\",\n        \"preparation_type\": \"KETO\",\n        \"spice_level\": \"low spicy\",\n        \"tenure\": 3\n      },\n      \"availability\": {\n        \"is_open\": true,\n        \"next_change_time\": 1214393434\n      },\n      \"inventory\": {\n        \"remaining_count\": 5\n      }\n    }\n  ]\n}";

	@GetMapping("/availability/get/meals")
	public String api1() {
		return get_meals_availability;
	}

	@PostMapping("/listing/get/meals-meta")
	public String api2() {
		return get_meals_meta;
	}

	@GetMapping("/availability/get/plans")
	public String api3() {
		return get_plans_availability;
	}

	@PostMapping("/listing/get/plans-meta")
	public String api4() {
		return get_plans_meta;
	}

	@GetMapping("/listing/get/addons")
	public String api5() {
		return addon_list_json;
	}

	@GetMapping("/listing/get/checkout-plan-meta")
	public String api6() {
		return checkout_plan_meta;
	}

	@PostMapping("/serve-daily/plans/")
	public String api7(@RequestParam("include-only") String include) {
		if (include.equals("AVAILABILITY,INVENTORY")) {
			return get_plan_avail_v2;
		} else if (include.equals("LIST-META")) {
			return get_plan_meta_v2;
		}
		return null;
	}

	@PostMapping("/serve-daily/products/")
	public String api8(@RequestParam("include-only") String include) {
		if (include.equals("AVAILABILITY,INVENTORY")) {
			return get_prod_avail_v2;
		} else if (include.equals("LIST-META")) {
			return get_prod_meta_v2;
		}
		return null;

	}
}
